
<div id="print_page">
	<div class="sub_print">
		<div class="print_header">
			<div class="page_inner">
				<div class="logo_print">
                    <img src="<?php echo $this->getViewFileUrl('images/logo_print.png'); ?>" alt="" />	
				</div>
				<form class="form_input" action="" method="POST" role="form">
					<div class="form-group">
						<p>
							<label for="">Name: </label>
							<input type="text">
						</p>
						<p>
							<label for="">GEBURTSDATUM:</label>
							<input type="text">
						</p>
					</div>
				</form>
			</div>
		</div>
		<div class="print_content">
			<div class="page_inner">
				<div class="right_content">
					<div class="p_title">
						<h3>Beratungs- und Abholstandorte</h3>
					</div>
					<div class="maps">
						<ul>
							<li class="even">
								<div class="address">
									<h4>Hauptstandort</h4>
									<strong>orthopunkt Solothurn</strong>
									<p>Schöngrünstrasse 35 <br>4500 Solothurn</p>
									<p class="telephong">Telefon: 032 623 00 53</p>
								</div>
								<div class="img_map">
                                    <img src="<?php echo $this->getViewFileUrl('images/maps1.jpg'); ?>" alt="" />	
								</div>
							</li>
							<li>
								<div class="address">
									
									<strong>orthopunkt Rothrist</strong>
									<p>Bernstrasse 86 <br>4852 Rothrist</p>
									<p class="telephong">Telefon: 062 206 00 90</p>
								</div>
								<div class="img_map">
                                    <img src="<?php echo $this->getViewFileUrl('images/maps2.jpg'); ?>" alt="" />								</div>
							</li>
							<!-- <li style="clear: left">
								<div class="address">
									
									<strong>orthopunkt Burgdorf</strong>
									<p>Mühlegasse 3 <br>3400 Burgdorf</p>
									<p class="telephong">Telefon: 034 424 01 85</p>
								</div>
								<div class="img_map">
                                    <img src="<?php echo $this->getViewFileUrl('images/maps3.jpg'); ?>" alt="" />
								</div>
							</li> -->
						</ul>
					</div>
				</div>
				<div class="left_content">
						<div class="box box1">
							<div class="p_title">
								<h3>HILFSMITTEL</h3>
							</div>
							<div class="hilfsmittel">
								
								<div class="details">
									<h4 class="product_name">
										
									</h4>
									<p class="product_sku">
										
									</p>
									
								</div>
							</div>
							<div class="text_content">
								<span>VERORDNET DURCH</span>
								<span>UNTERSCHRIFT, DATUM</span>
							</div>
						</div>
						<div class="box box2">
							<div class="p_title">
								<h3>DIAGNOSE</h3>
							</div>
							<div class="diagnose_content">
								
							</div>
						</div>
				</div>
				<div class="middle_content">
					<div class="check_code">
                        <img src="<?php echo $this->getViewFileUrl('images/code.png'); ?>" alt="" />	
					</div>
				</div>
			</div>
		</div>
		<div class="print_footer">
			<p>Wir freuen uns auf Ihre telefonische Voranmeldung, oder reservieren Sie Ihren Termin online.</p>
		</div>
	</div>
</div>


